MPA_MoviePosterAwards.Web/Controllers/CelebController.cs
using MPA_MoviePosterAwards.BLL;
using MPA_MoviePosterAwards.Common;
using MPA_MoviePosterAwards.Model;
using MPA_MoviePosterAwards.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MPA_MoviePosterAwards.Web.Controllers
{
    public class CelebController : Controller
    {
        // GET: Celeb
        public ActionResult Index(string id)
        {
            if (id.IsBlank())
                return RedirectToAction("Index", "Home");
            if (!Basic_Celebrity_BLL.Exist(Guid.Parse(id)))
            {
                return HttpNotFound();
            }
            Basic_Celebrity_Info _basic_celeb = Basic_Celebrity_BLL.GetSingle(Guid.Parse(id));
            CelebViewModel movie = new CelebViewModel(_basic_celeb);
            return View(movie);
        }

        // GET: Celeb/List/
        public ActionResult List()
        {
            List<CelebViewModel> celebs = new List<CelebViewModel>();
            foreach (var item in Basic_Celebrity_BLL.GetList(string.Empty))
            {
                CelebViewModel celeb = new CelebViewModel(item);
                celebs.Add(celeb);
            }
            return View(celebs);
        }

        // GET: Celeb/Update/
        public ActionResult Update(string id, string returnurl)
        {
            Basic_Celebrity_Info celeb = Basic_Celebrity_BLL.GetSingle(Guid.Parse(id));
            Basic_Celebrity_BLL.Delete(celeb.Id);
            CelebManager.InsertCeleb(celeb.Douban, celeb.Id);
            return Redirect(returnurl);
        }

        // GET: Celeb/Delete/
        public ActionResult Delete(string id, string returnurl)
        {
            Basic_Celebrity_Info celeb = Basic_Celebrity_BLL.GetSingle(Guid.Parse(id));
            Basic_Celebrity_BLL.Delete(celeb.Id);
            return Redirect(returnurl);
        }
    }
}

MPA_MoviePosterAwards.Web/Controllers/MovieController.cs
using MPA_MoviePosterAwards.BLL;
using MPA_MoviePosterAwards.Common;
using MPA_MoviePosterAwards.Model;
using MPA_MoviePosterAwards.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MPA_MoviePosterAwards.Web.Controllers
{
    public class MovieController : Controller
    {
        // GET: Movie
        public ActionResult Index(string id)
        {
            if (id.IsBlank())
                return RedirectToAction("Index", "Home");
            if (!Basic_Movie_BLL.Exist(Guid.Parse(id)))
            {
                return HttpNotFound();
            }
            Basic_Movie_Info _basic_movie = Basic_Movie_BLL.GetSingle(Guid.Parse(id));
            MovieViewModel movie = new MovieViewModel(_basic_movie);
            return View(movie);
        }

        // GET: Movie/List/
        public ActionResult List()
        {
            List<MovieViewModel> movies = new List<MovieViewModel>();
            foreach (var item in Basic_Movie_BLL.GetList(string.Empty).OrderBy(p => p.Title))
            {
                MovieViewModel movie = new MovieViewModel(item);
                movies.Add(movie);
            }
            return View(movies);
        }

        // GET: Movie/Create/
        public ActionResult Create()
        {
            return View();
        }

        // POST: Movie/Create/
        [HttpPost]
        public ActionResult Create(string douban)
        {
            foreach (var item in douban.Replace("\r\n", " ").Replace("\r", " ").Replace("\n", " ").Split(' '))
            {
                var result = MovieManager.InsertMovie(item, Guid.Empty);

                ModelState.AddModelError("", result.Error);
            }
            return View();
        }

        // GET: Movie/Update/
        public ActionResult Update(string id, string returnurl)
        {
            MovieManager.UpdateMovie(Guid.Parse(id));
            return Redirect(returnurl);
        }

        // GET: Movie/Delete/
        public ActionResult Delete(string id, string returnurl)
        {
            Basic_Movie_Info movie = Basic_Movie_BLL.GetSingle(Guid.Parse(id));
            Basic_Movie_BLL.Delete(movie.Id);
            return Redirect(returnurl);
        }

        // POST: /Movie/GetPosters
        [HttpPost]
        public JsonResult GetPosters(string id)
        {
            JsonResult json = new JsonResult();
            json.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            var posters = Basic_Poster_BLL.GetList(Guid.Parse(id));
            json.Data = posters.Select(p => new
            {
                id = p.Id.ToString(),
                url = p.Poster_M,
                title = p.Poster
            });

            return json;
        }
    }
}

MPA_MoviePosterAwards.Web/Views/Shared/Popup.cshtml
@model MPA_MoviePosterAwards.Web.Models.PopupViewModel

<link href="~/Content/ms-popup.css" rel="stylesheet" />
<div class="ms-popup-body" style="height: @Model.Height; width: @Model.Width; padding:0; overflow: hidden; font-size: 16px; font-family: Helvetica Neue,Helvetica,Arial,Hiragino Sans GB,STHeiti,Microsoft YaHei,Wenquanyi Micro Hei,sans-serif; color: #FFFFFF;">
    <div style="display:block; background-color:#FF3300; height:40px;">
        <span style="padding:10px 0px 10px 20px; font-weight:bold; font-size:20px; line-height:20px; display:inline-block;">@Model.Title</span>
        <button class="ms-popup-close" onclick="closeDialog();"><i class="fa fa-close"></i></button>
    </div>
    <iframe id="uploadFrame" src="@Model.Url"></iframe>
</div>
<div class="ms-popup-cover"></div>
<script src="~/Content/ms-popup.js"></script>
<script type="text/javascript">
    function openDialog() {
        $('.ms-popup-body').msPopup('show');
        $('.ms-popup-body iframe').attr('src', $('.ms-popup-body iframe').attr('src'));
    }
    function closeDialog() {
        $('.ms-popup-body').msPopup('hide');
    }
    $(document).ready(function () {
        $('nav').addClass('ms-popup-contents');
        $('footer').addClass('ms-popup-contents');
        $('.ms-popup-body iframe').width($('.ms-popup-body')[0].clientWidth);
        $('.ms-popup-body iframe').height($('.ms-popup-body')[0].clientHeight - 40);
    });
</script>

MPA_MoviePosterAwards.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @System.Configuration.ConfigurationManager.AppSettings["WebsiteSubTitle"]</title>
    <link href="~/Content/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/Common.css" rel="stylesheet" />
    <link href="~/Content/ms-navbar.css" rel="stylesheet" />
    <script src="~/Content/jquery.js"></script>
    <script src="~/Content/ms-navbar.js"></script>
</head>
<body>
    <nav class="ms-navbar ms-navbar-default">
        <div class="ms-container ms-navbar-bg">
            <a class="ms-navbar-brand" href="/Home/Index">@System.Configuration.ConfigurationManager.AppSettings["WebsiteTitle"]</a>
            <ul class="ms-nav ms-navbar-nav">
                <li class="nav-home">@Html.ActionLink("首页", "Index", "Home")</li>
                <li class="nav-movie">@Html.ActionLink("电影", "List", "Movie")</li>
                <li class="nav-celeb">@Html.ActionLink("影人", "List", "Celeb")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </nav>

    @RenderBody()

    <style>
        .ms-footer-sub {
            background-color: #252525;
            height: 20px;
            line-height: 20px;
            text-align: center;
        }

        .ms-footer {
            background-color: #FF3300;
            color: #FDFDFD;
            text-align: center;
            overflow: hidden;
        }

        footer {
            clear: both;
        }
    </style>
    <footer>
        <div class="ms-footer-sub">

        </div>
        <div class="ms-footer">
            <p style="margin:30px 0;">&copy; @DateTime.Now.Year - @System.Configuration.ConfigurationManager.AppSettings["WebsiteTitle"] - @System.Configuration.ConfigurationManager.AppSettings["WebsiteSubTitle"]</p>
        </div>
    </footer>
</body>
</html>