MPA_MoviePosterAwards.Web/Models/PosterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MPA_MoviePosterAwards.Web.Models
{
    public class PosterViewModel
    {
        public string Id { get; set; }
        public string Movie { get; set; }
        public string Poster { get; set; }
        public string Poster_M { get; set; }
        public string Poster_S { get; set; }
        public string Poster_XS { get; set; }
        public string Time { get; set; }
        public bool Active { get; set; } = false;
        public int Height { get; set; }
        public int Width { get; set; }
    }

    public class PosterIndexViewModel
    {
        public List<PosterViewModel> Posters { get; set; }
        public PosterViewModel ActivePoster { get; set; }
        public MovieViewModel Movie { get; set; }
        public UserViewModel User { get; set; }
    }

    public class NewestPosterViewModel
    {
        public string Url { get; set; }
        public string ID { get; set; }
        public string MovieID { get; set; }
        public string MovieTite { get; set; }
        public string Time { get; set; }
    }
}

MPA_MoviePosterAwards.Web/Controllers/PosterController.cs
using MPA_MoviePosterAwards.BLL;
using MPA_MoviePosterAwards.Model;
using MPA_MoviePosterAwards.Web.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MPA_MoviePosterAwards.Web.Controllers
{
    public class PosterController : Controller
    {
        // GET: Poster
        public ActionResult Index(string id)
        {
            var poster = Basic_Poster_BLL.GetSingle(Guid.Parse(id));

            PosterIndexViewModel model = new PosterIndexViewModel();

            model.Posters = Basic_Poster_BLL.GetList(poster.Movie).Select(p => new PosterViewModel
            {
                Id = p.Id.ToString(),
                Movie = p.Movie.ToString(),
                Poster = p.Poster,
                Poster_M = p.Poster_M,
                Poster_S = p.Poster_S,
                Poster_XS = p.Poster_XS,
                Time = p.Time.ToString("yyyy年MM月dd日 hh:mm:ss"),
                Active = p.Id == poster.Id,
                Height = p.Height,
                Width = p.Width
            }).ToList();
            model.ActivePoster = model.Posters.FirstOrDefault(p => p.Active);
            model.User = new UserViewModel(Basic_User_BLL.GetSingle(poster.User));
            model.Movie = new MovieViewModel(Basic_Movie_BLL.GetSingle(poster.Movie));

            return View(model);
        }

        // GET: Poster/Create/
        public ActionResult Create(string movie)
        {
            PosterViewModel poster = new PosterViewModel();
            poster.Movie = movie;
            return View(poster);
        }

        // POST: Poster/Create/
        [HttpPost]
        public ActionResult Create(PosterViewModel model, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (file != null && file.ContentLength > 0)
            {
                string filename = PosterManager.GetPosterName(model.Movie);
                var poster = Path.Combine(Request.MapPath("~/Resources/Poster/"), filename + Path.GetExtension(file.FileName));
                var poster_m = Path.Combine(Request.MapPath("~/Resources/Poster_M/"), filename + "_M" + Path.GetExtension(file.FileName));
                var poster_s = Path.Combine(Request.MapPath("~/Resources/Poster_S/"), filename + "_S" + Path.GetExtension(file.FileName));
                var poster_xs = Path.Combine(Request.MapPath("~/Resources/Poster_XS/"), filename + "_XS" + Path.GetExtension(file.FileName));
                file.SaveAs(poster);
                model.Poster = Path.GetFileName(poster);
                model.Poster_M = Path.GetFileName(poster_m);
                model.Poster_S = Path.GetFileName(poster_s);
                model.Poster_XS = Path.GetFileName(poster_xs);

                Bitmap bmpSrc = new Bitmap(poster);
                Compress(bmpSrc, (int)((double)bmpSrc.Width / bmpSrc.Height * 800), 800, poster_m);
                Compress(bmpSrc, (int)((double)bmpSrc.Width / bmpSrc.Height * 400), 400, poster_s);
                Compress(bmpSrc, (int)((double)bmpSrc.Width / bmpSrc.Height * 200), 200, poster_xs);
                Basic_Poster_Info _basic_poster = new Basic_Poster_Info
                {
                    Id = Guid.NewGuid(),
                    Movie = Guid.Parse(model.Movie),
                    User = Guid.Parse(Common.CookieHelper.GetCookie("userid")),
                    Poster = model.Poster,
                    Poster_M = model.Poster_M,
                    Poster_S = model.Poster_S,
                    Poster_XS = model.Poster_XS,
                    Height = bmpSrc.Height,
                    Width = bmpSrc.Width,
                    Time = DateTime.Now
                };
                Basic_Poster_BLL.Insert(_basic_poster);
            }
            else
            {
                ModelState.AddModelError("", "请选择一张图片");
            }
            return View(model);
        }

        public void Compress(Bitmap source, int width, int height, string filename)
        {
            Bitmap bmpDest = new Bitmap(width, height);
            Graphics g = Graphics.FromImage(bmpDest);

            g.SmoothingMode = SmoothingMode.HighQuality;
            g.InterpolationMode = InterpolationMode.HighQualityBicubic;
            Rectangle rectDest = new Rectangle(0, 0, bmpDest.Width, bmpDest.Height);
            Rectangle rectSrc = new Rectangle(0, 0, source.Width, source.Height);
            g.DrawImage(source, rectDest, rectSrc, GraphicsUnit.Pixel);
            bmpDest.Save(filename, System.Drawing.Imaging.ImageFormat.Jpeg);//带上Jpeg压缩格式，可以让图片进行压缩

            g.Dispose();
            bmpDest.Dispose();
        }

    }
}

MPA_MoviePosterAwards.Web/Views/Poster/Create.cshtml
@model MPA_MoviePosterAwards.Web.Models.PosterViewModel

@{
    ViewBag.Title = "新增海报";
}

<h2>新增海报</h2>

@using (Html.BeginForm("Create", "Poster", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div>
        @Html.HiddenFor(model => model.Movie)
        <input type="file" name="file" class="form-control" placeholder="请选择图片" onchange="loadImageFile()" id="inputImg" />
        @Html.ValidationMessageFor(model => model.Poster, "", new { @class = "text-danger" })
    </div>

    <div style="padding-top:15px; padding-bottom:15px;">
        <div>
            <label class="control-label">已选择的图片</label>
        </div>
        <img class="img-thumbnail" id="imgDisplay" style="max-width:147px;min-width:64px; max-height:147px;" />
    </div>

    <div class="full-width">
        <input type="submit" value="确认更改头像" class="btn btn-primary" />
    </div>
}

<script type="text/javascript">
    var loadImageFile = (function () {
        if (window.FileReader) {
            var oPreviewImg = null, oFReader = new window.FileReader(),
                rFilter = /^(?:image\/bmp|image\/cis\-cod|image\/gif|image\/ief|image\/jpeg|image\/jpeg|image\/jpeg|image\/pipeg|image\/png|image\/svg\+xml|image\/tiff|image\/x\-cmu\-raster|image\/x\-cmx|image\/x\-icon|image\/x\-portable\-anymap|image\/x\-portable\-bitmap|image\/x\-portable\-graymap|image\/x\-portable\-pixmap|image\/x\-rgb|image\/x\-xbitmap|image\/x\-xpixmap|image\/x\-xwindowdump)$/i;

            oFReader.onload = function (oFREvent) {
                var newPreview = document.getElementById("imgDisplay");
                newPreview.setAttribute("src", oFREvent.target.result);
            };
            return function () {
                var aFiles = document.getElementById("inputImg").files;
                if (aFiles.length === 0) { return; }
                if (!rFilter.test(aFiles[0].type)) { alert("You must select a valid image file!"); return; }
                oFReader.readAsDataURL(aFiles[0]);
            }
        }
        if (navigator.appName === "Microsoft Internet Explorer") {
            return function () {
                alert(document.getElementById("inputImg").value);
                document.getElementById("imgDisplay").src = document.getElementById("inputImg").value;
            }
        }
    })();
</script>

MPA_MoviePosterAwards.Web/Views/Poster/Index.cshtml
@model MPA_MoviePosterAwards.Web.Models.PosterIndexViewModel

@{
    ViewBag.Title = Model.ActivePoster.Poster;
}

<style>
    .ms-pic {
        /*background-color: #AAAAAA;
        padding: 5px;*/
        text-align: center;
    }

    .ms-pic-display {
        background-color: #EEEEEE;
        height: 560px;
        /*padding: 5px 5px 20px 5px;*/
    }

        .ms-pic-display div {
            height: 100%;
            width: auto;
            position: relative;
            overflow: hidden;
            /*子元素垂直居中*/
            display: -webkit-flex;
            display: flex;
            -webkit-align-items: center;
            align-items: center;
            -webkit-justify-content: center;
            justify-content: center;
        }

        .ms-pic-display img {
            height: 100%;
            width: auto;
        }

            .ms-pic-display img.wide {
                width: 100%;
                height: auto;
            }

        .ms-pic-display a {
            position: absolute;
            right: 0;
            bottom: -3.2em;
            width: 100%;
            font-size: 1.6em;
            line-height: 1.6em;
            padding: 0.8em;
            text-align: center;
            text-decoration: none;
            background-color: rgba(0, 0, 0, 0.5);
            color: #F1F1F1;
            transition: all 0.25s ease;
            border-radius: 0;
            border-top: 1px solid #FFFFFF;
        }

            .ms-pic-display a:hover {
                background-color: rgba(0, 0, 0, 0.75);
            }

        .ms-pic-display div:hover a {
            bottom: 0;
        }


    .ms-pic-prev {
        background-color: #CCCCCC;
        /*padding: 5px;*/
        text-align: center;
    }

        .ms-pic-prev > ul {
            list-style: none;
            padding: 5px 5px 0px 0px;
            margin: 0;
            display: inline-block;
            text-align: center;
        }

            .ms-pic-prev > ul li {
                height: 125px;
                display: inline-block;
                margin: 0px 0px 5px 5px;
                padding: 0;
                transition: all 0.25s ease;
            }

                .ms-pic-prev > ul li img {
                    height: 100%;
                    transition: inherit;
                }

                .ms-pic-prev > ul li.selected {
                }

                    .ms-pic-prev > ul li.selected img {
                        transform: translateY(-15px);
                        box-shadow: 0px 10px 10px rgba(0,0,0,0.8);
                    }
</style>

<div class="ms-container" style="padding:0px;">
    <div>

    </div>
    <div class="ms-pic">
        <div class="ms-pic-display">
            @foreach (var item in Model.Posters)
            {
                if (item.Active)
                {
                    <div>
                        <img src="~/Resources/Poster_M/@item.Poster_M" />
                        <a href="/Resources/Poster/@item.Poster" target="_blank">点击查看大图</a>
                    </div>
                }
            }
        </div>
        <div class="ms-pic-prev">
            <ul>
                @foreach (var item in Model.Posters)
                {
                    if (item.Active)
                    {
                        <li class="selected">
                            <img src="~/Resources/Poster_S/@item.Poster_S" />
                        </li>
                    }
                    else
                    {
                        <li>
                            <a href="/Poster/Index?id=@item.Id" title="@item.Poster"><img src="~/Resources/Poster_S/@item.Poster_S" /></a>
                        </li>
                    }
                }
            </ul>
        </div>
    </div>
</div>